package netdata.enums.ICMP;

public enum DESTINATION_UNREACHABLE {
	NET_UNREACHABLE,
	HOST_UNREACHABLE,
	PROTOCOL_UNREACHABLE,
	PORT_UNREACHABLE,
	FRAGMENTATION_NEEDED,
	SOURCE_ROUTE_FAIL,
	DESTINATION_NETWORK_UNKNOWN,
	DESTINATION_HOST_ISOLATED,
	SOURCE_HOST_ISOLATED,
	COMMUNICATION_DESTINATION_NETWORK_PROHIBITED,
	COMMUNICATION_DESTINATION_HOST_PROHIBITED,
	DESTINATION_NETWORK_UNREACHABLE,
	DESTINATION_HOST_UNREACHABLE,
	COMMUNICATION_PROHIBITED,
	HOST_PRECEDENCE_VIOLATION,
	PRECEDENCE_CUTOFF
}
